analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - windows/**
    - macos/**
    - linux/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/l10n/app_localizations*.dart
    - test/generated_migrations/**
include: ../analysis_options.yaml
